### ISSUE TITLE
C source files are not allowed when not using cgo: syscall.c

### ISSUE THREAD

**Issue by micksmix** [a-palchikov/wmi#1]
After running `go get github.com/a-palchikov/wmi`, I receive this error message:

c:\gopath\src\github.com\a-palchikov\wmi\wmi.go:4:2: C source files not allowed when not using cgo: syscall.c

I'm running Windows 7 x64 and `go version go1.4.2 windows/amd64`.

[Looking at the Go v1.4 release notes](https://golang.org/doc/go1.4#gocmd), this seems to be because the com-and-go package include a c source file, [syscall.c](https://code.google.com/p/com-and-go/source/browse/) and attempts to compile it upon installation.

> Unless cgo is being used to build the package, the go command now refuses to compile C source files, since the relevant C compilers (6c etc.) are intended to be removed from the installation in some future release. (They are used today only to build part of the runtime.) It is difficult to use them correctly in any case, so any extant uses are likely incorrect, so we have disabled them.

Do you know how to resolve or work around this error?

**Comment by a-palchikov** [comment]
@MicksMix Hey, sorry for the late reply.
It seems that the com-and-go project has been exported to gihub and the syscall issue fixed in the last commit: https://github.com/tianlin/com-and-go/commit/a2b35ebfc50741ef03b8546a64d956461215d7e4

**Comment by micksmix** [comment]
Thanks! Seems your example program to query Windows services no longer compiles though. Either that or I have a problem with my local configuration.

After updating the example to refer to the new com-and-go, I receive a few errors when attempting to run:

.\wmiSvc.go:12: cannot use nil as type uintptr in argument to "github.com/tianlin/com-and-go".CoInitializeEx
.\wmiSvc.go:20: too many arguments in call to "github.com/tianlin/com-and-go".CoCreateInstance
.\wmiSvc.go:20: multiple-value "github.com/tianlin/com-and-go".CoCreateInstance() in single-value context
.\wmiSvc.go:31: cannot use "github.com/tianlin/com-and-go".BStr literal (type "github.com/tianlin/com-and-go".BStr) as type "github.com/tianlin/com-and-go/v2".BStr in argument to wmi.CoSetProxyBlanket

**Comment by micksmix** [comment]
Never mind...I figured out I needed to change the import on the example to:

```
import (
    "github.com/tianlin/com-and-go/v2"
    "github.com/a-palchikov/wmi"
    "fmt"
    "log"
    "unsafe"
)
```

I left off the `/v2` for the updated "github.com/tianlin/com-and-go"
